[package]
name = "lincheck"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
loom = "0.5"
quickcheck = "1.0"

[dev-dependencies]
quickcheck_macros = "1.0"

